services:
  
  backend:
    build:
      context: ./backend-rust
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo1:27017/attendance-geotag
      - REDIS_URL=redis://:${REDIS_PASSWORD:-redis_secure_password}@redis:6379
    volumes:
      - ./backend-rust/src:/app/src:ro

  
  mongodb-init:
    entrypoint: ["mongosh", "--host", "mongo1", "--port", "27017", "/init-mongo.js"]
