use chrono::{DateTime, NaiveDate, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A batch of students generated by the Excel-upload bulk session creation
/// flow. Deliberately a separate table from `batches`/`students` — see
/// migration 0003 for the rationale.
#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
#[serde(rename_all = "camelCase")]
pub struct ExcelBatch {
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub source_filename: Option<String>,
    pub session_date: NaiveDate,
    pub track: String,
    pub class_label: String,
    pub session_time_raw: String,
    pub duration_minutes: i32,
    pub college_name: Option<String>,
    pub raw_mentor_emails: Vec<String>,
    pub created_by: Uuid,
    pub created_at: DateTime<Utc>,
}

impl ExcelBatch {
    pub fn table_name() -> &'static str {
        "excel_batches"
    }
}

/// A persisted excel-batch student row (own table, FK'd to `excel_batches`).
#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
#[serde(rename_all = "camelCase")]
pub struct ExcelBatchStudent {
    pub id: Uuid,
    pub excel_batch_id: Uuid,
    pub position: i32,
    pub name: String,
    pub roll_number: String,
    pub email: Option<String>,
    pub round: Option<String>,
}

/// Student payload as parsed/edited by the upload-review UI (no id/batch/
/// position — assigned at insert time). Kept separate from
/// `batch::StudentInput` since it carries the extra `round` field and has no
/// `college_name` (the master template has no such column).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExcelStudentInput {
    pub name: String,
    pub roll_number: String,
    pub email: Option<String>,
    pub round: Option<String>,
}
