use axum::{extract::State, http::Request, middleware::Next, response::Response};
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use hmac::{Hmac, KeyInit, Mac};
use sha2::Sha256;
use std::sync::Arc;
use subtle::ConstantTimeEq;

use crate::error::{AppError, Result};

/// Cookie name that holds the CSRF token (NOT HttpOnly — JS must read it).
pub const CSRF_COOKIE_NAME: &str = "csrf_token";

/// Header name the frontend must echo back on mutating requests.
pub const CSRF_HEADER_NAME: &str = "x-csrf-token";

/// Generates a signed CSRF token: `<random_bytes_b64>.<HMAC-SHA256(secret, random_bytes)_b64>`
///
/// Signing prevents cookie-tossing attacks where a network attacker who can
/// set cookies (e.g. via a subdomain) tries to inject a token they know.
pub fn generate_csrf_token(secret: &str) -> String {
    let random: [u8; 32] = rand::random();
    let raw = URL_SAFE_NO_PAD.encode(random);
    let sig = sign_csrf(&raw, secret);
    format!("{}.{}", raw, sig)
}

/// Verifies that:
/// 1. The cookie and header values are identical (double-submit check).
/// 2. The token's signature is valid (was generated by this server).
///
/// Both checks run in constant time to prevent timing oracle attacks.
pub fn verify_csrf_token(cookie_value: &str, header_value: &str, secret: &str) -> bool {
    // Constant-time equality check between cookie and header
    let values_match: bool = cookie_value
        .as_bytes()
        .ct_eq(header_value.as_bytes())
        .into();
    if !values_match {
        return false;
    }

    // Validate HMAC signature
    let Some((raw, sig)) = cookie_value.split_once('.') else {
        return false;
    };
    let expected = sign_csrf(raw, secret);
    expected.as_bytes().ct_eq(sig.as_bytes()).into()
}

fn sign_csrf(value: &str, secret: &str) -> String {
    let mut mac =
        Hmac::<Sha256>::new_from_slice(secret.as_bytes()).expect("HMAC accepts any key length");
    mac.update(value.as_bytes());
    URL_SAFE_NO_PAD.encode(mac.finalize().into_bytes())
}

/// Extracts a named cookie value from the `Cookie` header.
fn extract_cookie<'a>(cookie_header: &'a str, name: &str) -> Option<&'a str> {
    let prefix = format!("{}=", name);
    cookie_header.split(';').find_map(|part| {
        let part = part.trim();
        part.strip_prefix(prefix.as_str())
    })
}

/// True when a request authenticates with only `Authorization: Bearer ...`
/// and carries no `admin_token` cookie at all — the case that exempts a
/// mutating request from CSRF validation (see `csrf_middleware`'s doc
/// comment for the full rationale). Takes raw header values instead of an
/// `axum::http::HeaderMap` so it's trivially unit-testable without spinning
/// up an `AppState`/full request.
fn is_cookieless_bearer_request(auth_header: Option<&str>, cookie_header: Option<&str>) -> bool {
    let has_bearer = auth_header
        .map(|v| v.starts_with("Bearer "))
        .unwrap_or(false);
    let has_auth_cookie = cookie_header
        .and_then(|h| extract_cookie(h, crate::middleware::AUTH_COOKIE_NAME))
        .is_some();
    has_bearer && !has_auth_cookie
}

/// CSRF protection middleware for admin routes.
///
/// # GET / safe methods
/// Issues or refreshes the CSRF cookie without blocking the request. The
/// cookie is NOT HttpOnly so the React admin frontend can read it with JS and
/// echo it as the `x-csrf-token` header on subsequent mutations.
///
/// # POST / PUT / PATCH / DELETE
/// Validates that the `x-csrf-token` header matches the `csrf_token` cookie
/// AND that the token carries a valid HMAC signature. Rejects with 403 if
/// either check fails.
///
/// # Bearer-token requests (no cookie)
/// A request authenticated with only `Authorization: Bearer <token>` and no
/// `admin_token` cookie (e.g. the Expo mentor app) skips this check
/// entirely — see the bypass block below for why that's safe.
///
/// `SameSite=Strict` on the auth cookie already prevents cross-site requests
/// from carrying the session, so this adds defence-in-depth against any edge
/// case where SameSite alone is insufficient (older browsers, subdomain issues).
pub async fn csrf_middleware(
    State(state): State<Arc<crate::AppState>>,
    request: Request<axum::body::Body>,
    next: Next,
) -> Result<Response> {
    let is_safe_method = matches!(
        request.method().as_str(),
        "GET" | "HEAD" | "OPTIONS" | "TRACE"
    );

    if is_safe_method {
        // For safe methods: let the request through and attach a fresh CSRF
        // cookie only if one is not already present or is invalid. Rotating
        // a still-valid token on every GET creates a race: pages that fire
        // several parallel GETs (e.g. a dashboard loading multiple
        // resources) each try to overwrite the cookie, so a POST fired
        // moments later can read a header value from one response while the
        // browser's cookie jar has already been updated by another
        // response's Set-Cookie — header and cookie then legitimately
        // mismatch even though the user did nothing wrong. The token has no
        // expiry (pure random + HMAC signature), so there's no need to
        // reissue it as long as it still verifies.
        let existing_cookie = request
            .headers()
            .get(axum::http::header::COOKIE)
            .and_then(|v| v.to_str().ok())
            .and_then(|h| extract_cookie(h, CSRF_COOKIE_NAME));
        let needs_new_token = match existing_cookie {
            Some(c) => match c.split_once('.') {
                Some((raw, sig)) => {
                    let expected = sign_csrf(raw, &state.config.jwt_secret);
                    !bool::from(expected.as_bytes().ct_eq(sig.as_bytes()))
                }
                None => true,
            },
            None => true,
        };

        let mut response = next.run(request).await;
        if !needs_new_token {
            return Ok(response);
        }
        let token = generate_csrf_token(&state.config.jwt_secret);
        let is_prod = state.config.is_production();
        let secure_flag = if is_prod { "; Secure" } else { "" };
        // Path=/ (not /api): this cookie is deliberately NOT HttpOnly so the
        // React admin SPA can read it via `document.cookie` and echo it as
        // the x-csrf-token header. Browsers only expose a cookie through
        // `document.cookie` on pages whose own path matches the cookie's
        // Path — the admin SPA is served at /owner-of-attendix-xyz/, which
        // doesn't match Path=/api, so axios could never see the cookie to
        // echo it back, and every mutating admin request 403'd with "CSRF
        // token missing from request headers" even though the cookie itself
        // was being sent to the server correctly.
        let cookie = format!(
            "{}={}; SameSite=Strict; Path=/{}",
            CSRF_COOKIE_NAME, token, secure_flag
        );
        if let Ok(val) = axum::http::HeaderValue::from_str(&cookie) {
            response
                .headers_mut()
                .insert(axum::http::header::SET_COOKIE, val);
        }
        return Ok(response);
    }

    // Native clients (the Expo mentor app) authenticate with only an
    // Authorization: Bearer header and never carry the admin_token cookie —
    // there's no cookie jar involved at all. CSRF exploits a browser's
    // *automatic* attachment of ambient cookie credentials to a forged
    // cross-site request; a request that instead relies on a header the
    // attacking page has to set explicitly (and couldn't, without first
    // clearing this API's strict CORS origin allowlist — which native
    // callers aren't subject to in the first place, since they're not
    // browsers) isn't a CSRF vector. This runs after auth_middleware in the
    // layer stack (see routes/admin.rs), so the JWT is already validated by
    // this point — this check only classifies transport, it doesn't
    // authenticate anything. Any request that *also* carries the cookie
    // still falls through to the full double-submit check below, so this
    // can never widen into a bypass for cookie-based (browser) clients.
    let auth_header = request
        .headers()
        .get(axum::http::header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok());
    let cookie_header_str = request
        .headers()
        .get(axum::http::header::COOKIE)
        .and_then(|v| v.to_str().ok());
    if is_cookieless_bearer_request(auth_header, cookie_header_str) {
        return Ok(next.run(request).await);
    }

    // For mutating methods: validate the double-submit token
    let cookie_header = request
        .headers()
        .get(axum::http::header::COOKIE)
        .and_then(|v| v.to_str().ok())
        .unwrap_or("");

    let cookie_val = extract_cookie(cookie_header, CSRF_COOKIE_NAME);

    let header_val = request
        .headers()
        .get(CSRF_HEADER_NAME)
        .and_then(|v| v.to_str().ok());

    match (cookie_val, header_val) {
        (Some(c), Some(h)) if verify_csrf_token(c, h, &state.config.jwt_secret) => {
            Ok(next.run(request).await)
        }
        (None, _) => Err(AppError::Forbidden(
            "CSRF cookie missing. Load the admin panel before submitting requests.".to_string(),
        )),
        (_, None) => Err(AppError::Forbidden(
            "CSRF token missing from request headers (x-csrf-token).".to_string(),
        )),
        _ => Err(AppError::Forbidden(
            "CSRF validation failed. Token invalid or expired.".to_string(),
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SECRET: &str = "a-test-secret-that-is-long-enough-for-hmac";

    #[test]
    fn valid_token_passes() {
        let token = generate_csrf_token(SECRET);
        assert!(verify_csrf_token(&token, &token, SECRET));
    }

    #[test]
    fn mismatched_cookie_and_header_fails() {
        let t1 = generate_csrf_token(SECRET);
        let t2 = generate_csrf_token(SECRET);
        assert!(!verify_csrf_token(&t1, &t2, SECRET));
    }

    #[test]
    fn tampered_token_fails() {
        let token = generate_csrf_token(SECRET);
        let tampered = format!("{}TAMPERED", token);
        assert!(!verify_csrf_token(&tampered, &tampered, SECRET));
    }

    #[test]
    fn wrong_secret_fails() {
        let token = generate_csrf_token(SECRET);
        assert!(!verify_csrf_token(&token, &token, "different-secret"));
    }

    #[test]
    fn bearer_without_cookie_is_exempt() {
        assert!(is_cookieless_bearer_request(
            Some("Bearer abc.def.ghi"),
            None
        ));
    }

    #[test]
    fn bearer_with_unrelated_cookie_is_exempt() {
        // A cookie header that doesn't contain admin_token (e.g. some other
        // site's cookie riding along) must not defeat the exemption.
        assert!(is_cookieless_bearer_request(
            Some("Bearer abc.def.ghi"),
            Some("some_other_cookie=value")
        ));
    }

    // Regression guard: a request that carries the admin_token cookie must
    // never be exempted, even if it also happens to send a Bearer header —
    // this is what keeps the exemption from ever widening into a bypass for
    // cookie-based (browser) clients.
    #[test]
    fn bearer_with_admin_token_cookie_is_not_exempt() {
        assert!(!is_cookieless_bearer_request(
            Some("Bearer abc.def.ghi"),
            Some("admin_token=some-jwt; other=1")
        ));
    }

    #[test]
    fn no_bearer_header_is_not_exempt() {
        assert!(!is_cookieless_bearer_request(None, None));
        assert!(!is_cookieless_bearer_request(Some("Basic xyz"), None));
    }
}
