use axum::{extract::State, http::Request, middleware::Next, response::Response};
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use hmac::{Hmac, KeyInit, Mac};
use sha2::Sha256;
use std::sync::Arc;
use subtle::ConstantTimeEq;

use crate::error::{AppError, Result};

/// Cookie name that holds the CSRF token (NOT HttpOnly — JS must read it).
pub const CSRF_COOKIE_NAME: &str = "csrf_token";

/// Header name the frontend must echo back on mutating requests.
pub const CSRF_HEADER_NAME: &str = "x-csrf-token";

/// Generates a signed CSRF token: `<random_bytes_b64>.<HMAC-SHA256(secret, random_bytes)_b64>`
///
/// Signing prevents cookie-tossing attacks where a network attacker who can
/// set cookies (e.g. via a subdomain) tries to inject a token they know.
pub fn generate_csrf_token(secret: &str) -> String {
    let random: [u8; 32] = rand::random();
    let raw = URL_SAFE_NO_PAD.encode(random);
    let sig = sign_csrf(&raw, secret);
    format!("{}.{}", raw, sig)
}

/// Verifies that:
/// 1. The cookie and header values are identical (double-submit check).
/// 2. The token's signature is valid (was generated by this server).
///
/// Both checks run in constant time to prevent timing oracle attacks.
pub fn verify_csrf_token(cookie_value: &str, header_value: &str, secret: &str) -> bool {
    // Constant-time equality check between cookie and header
    let values_match: bool = cookie_value
        .as_bytes()
        .ct_eq(header_value.as_bytes())
        .into();
    if !values_match {
        return false;
    }

    // Validate HMAC signature
    let Some((raw, sig)) = cookie_value.split_once('.') else {
        return false;
    };
    let expected = sign_csrf(raw, secret);
    expected.as_bytes().ct_eq(sig.as_bytes()).into()
}

fn sign_csrf(value: &str, secret: &str) -> String {
    let mut mac =
        Hmac::<Sha256>::new_from_slice(secret.as_bytes()).expect("HMAC accepts any key length");
    mac.update(value.as_bytes());
    URL_SAFE_NO_PAD.encode(mac.finalize().into_bytes())
}

/// Extracts a named cookie value from the `Cookie` header.
fn extract_cookie<'a>(cookie_header: &'a str, name: &str) -> Option<&'a str> {
    let prefix = format!("{}=", name);
    cookie_header.split(';').find_map(|part| {
        let part = part.trim();
        part.strip_prefix(prefix.as_str())
    })
}

/// CSRF protection middleware for admin routes.
///
/// # GET / safe methods
/// Issues or refreshes the CSRF cookie without blocking the request. The
/// cookie is NOT HttpOnly so the React admin frontend can read it with JS and
/// echo it as the `x-csrf-token` header on subsequent mutations.
///
/// # POST / PUT / PATCH / DELETE
/// Validates that the `x-csrf-token` header matches the `csrf_token` cookie
/// AND that the token carries a valid HMAC signature. Rejects with 403 if
/// either check fails.
///
/// `SameSite=Strict` on the auth cookie already prevents cross-site requests
/// from carrying the session, so this adds defence-in-depth against any edge
/// case where SameSite alone is insufficient (older browsers, subdomain issues).
pub async fn csrf_middleware(
    State(state): State<Arc<crate::AppState>>,
    request: Request<axum::body::Body>,
    next: Next,
) -> Result<Response> {
    let is_safe_method = matches!(
        request.method().as_str(),
        "GET" | "HEAD" | "OPTIONS" | "TRACE"
    );

    if is_safe_method {
        // For safe methods: let the request through and attach a fresh CSRF
        // cookie if one is not already present or is invalid.
        let mut response = next.run(request).await;
        let token = generate_csrf_token(&state.config.jwt_secret);
        let is_prod = state.config.is_production();
        let secure_flag = if is_prod { "; Secure" } else { "" };
        let cookie = format!(
            "{}={}; SameSite=Strict; Path=/api{}",
            CSRF_COOKIE_NAME, token, secure_flag
        );
        if let Ok(val) = axum::http::HeaderValue::from_str(&cookie) {
            response
                .headers_mut()
                .insert(axum::http::header::SET_COOKIE, val);
        }
        return Ok(response);
    }

    // For mutating methods: validate the double-submit token
    let cookie_header = request
        .headers()
        .get(axum::http::header::COOKIE)
        .and_then(|v| v.to_str().ok())
        .unwrap_or("");

    let cookie_val = extract_cookie(cookie_header, CSRF_COOKIE_NAME);

    let header_val = request
        .headers()
        .get(CSRF_HEADER_NAME)
        .and_then(|v| v.to_str().ok());

    match (cookie_val, header_val) {
        (Some(c), Some(h)) if verify_csrf_token(c, h, &state.config.jwt_secret) => {
            Ok(next.run(request).await)
        }
        (None, _) => Err(AppError::Forbidden(
            "CSRF cookie missing. Load the admin panel before submitting requests.".to_string(),
        )),
        (_, None) => Err(AppError::Forbidden(
            "CSRF token missing from request headers (x-csrf-token).".to_string(),
        )),
        _ => Err(AppError::Forbidden(
            "CSRF validation failed. Token invalid or expired.".to_string(),
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SECRET: &str = "a-test-secret-that-is-long-enough-for-hmac";

    #[test]
    fn valid_token_passes() {
        let token = generate_csrf_token(SECRET);
        assert!(verify_csrf_token(&token, &token, SECRET));
    }

    #[test]
    fn mismatched_cookie_and_header_fails() {
        let t1 = generate_csrf_token(SECRET);
        let t2 = generate_csrf_token(SECRET);
        assert!(!verify_csrf_token(&t1, &t2, SECRET));
    }

    #[test]
    fn tampered_token_fails() {
        let token = generate_csrf_token(SECRET);
        let tampered = format!("{}TAMPERED", token);
        assert!(!verify_csrf_token(&tampered, &tampered, SECRET));
    }

    #[test]
    fn wrong_secret_fails() {
        let token = generate_csrf_token(SECRET);
        assert!(!verify_csrf_token(&token, &token, "different-secret"));
    }
}
